### ISSUE TITLE
помоги

### ISSUE THREAD

**Issue by ghost** [MrLivixx/voicestats#1]
помоги

**Comment by EveryDayRains** [comment]
Нет описания проблемы.

**Comment by ghost** [comment]
ну я там все настрол че далше

**Comment by EveryDayRains** [comment]
Ну запускай бота node bot.js

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/60259215/74525650-9bdafa80-4f32-11ea-8fcb-9e93f94ce71d.png)

**Comment by EveryDayRains** [comment]
Полные лог пришли

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/60259215/74525722-dfcdff80-4f32-11ea-99b2-bdab2f380bb9.png)

**Comment by EveryDayRains** [comment]
Выше ещё

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/60259215/74525832-20c61400-4f33-11ea-99bf-9cf366752208.png)

**Comment by ghost** [comment]
ну че там проблем

**Comment by ghost** [comment]
ау

**Comment by ghost** [comment]
ау

**Comment by EveryDayRains** [comment]
npm i discord.js fs parse-ms

**Comment by ghost** [comment]
ау

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/60259215/74526608-c463f400-4f34-11ea-87e6-d58b2af3ffcf.png)

**Comment by ghost** [comment]
вот зайди я покажу че туту https://discord.gg/bQ5Q7V

**Comment by EveryDayRains** [comment]
У тебя модуль Квик бд не встал. Ставь бота на глитч и все будет работать

**Comment by ghost** [comment]
https://github.com/deni2222/-7777.git вот загрузил

**Comment by EveryDayRains** [comment]
Дай доступ в настройках и collaboration
